lists/gb/gb-gor.json

An update to the list with code GB-GOR has been proposed
**List title:** Government Organisation Register
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-GOR](http://org-id.guide/_preview_branch/GB-GOR)  (visiting [http://org-id.guide/list/GB-GOR](http://org-id.guide/list/GB-GOR) when the preview is active or check the files changed options above.

Updated  registry entry for 'Government Organisation Register' (GB-GOR)

---

lists/gb/gb-lae.json

An update to the list with code GB-LAE has been proposed
**List title:** Local Authorities for England Register
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-LAE](http://org-id.guide/_preview_branch/GB-LAE)  (visiting [http://org-id.guide/list/GB-LAE](http://org-id.guide/list/GB-LAE) when the preview is active or check the files changed options above.

Updated  registry entry for 'Local Authorities for England Register' (GB-LAE)

---

lists/gb/gb-pla.json

A new list has been proposed with the code GB-PLA
**List title:** Principal Local Authority Register for Wales
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-PLA](http://org-id.guide/_preview_branch/GB-PLA)  (visiting [http://org-id.guide/list/GB-PLA](http://org-id.guide/list/GB-PLA) when the preview is active or check the files changed options above.

New  registry entry for 'Principal Local Authority Register for Wales' (GB-PLA)

---

lists/ar/ar-cuit.json

A new list has been proposed with the code AR-CUIT
**List title:** Unique Tax Identification Code (Argentina)
Preview the platform with this list at [http://org-id.guide/_preview_branch/AR-CUIT](http://org-id.guide/_preview_branch/AR-CUIT)  (visiting [http://org-id.guide/list/AR-CUIT](http://org-id.guide/list/AR-CUIT) when the preview is active or check the files changed options above.

New  registry entry for 'Unique Tax Identification Code (Argentina)' (AR-CUIT)

---

lists/ng/ng-bpp.json

A new list has been proposed with the code NG-BPP
**List title:** Bureau of Public Procurement (BPP) Contractor Registration System (Nigeria)
Preview the platform with this list at [http://org-id.guide/_preview_branch/NG-BPP](http://org-id.guide/_preview_branch/NG-BPP)  (visiting [http://org-id.guide/list/NG-BPP](http://org-id.guide/list/NG-BPP) when the preview is active or check the files changed options above.

New  registry entry for 'Bureau of Public Procurement (BPP) Contractor Registration System (Nigeria)' (NG-BPP)

---

lists/pl/pl-krs.json

A new list has been proposed with the code PL-KRS
**List title:** The National Court Register (Poland)
Preview the platform with this list at [http://org-id.guide/_preview_branch/PL-KRS](http://org-id.guide/_preview_branch/PL-KRS)  (visiting [http://org-id.guide/list/PL-KRS](http://org-id.guide/list/PL-KRS) when the preview is active or check the files changed options above.

New  registry entry for 'The National Court Register (Poland)' (PL-KRS)

---

lists/pl/pl-regon.json

A new list has been proposed with the code PL-REGON
**List title:** REGON - Statistical number of an economy entity
Preview the platform with this list at [http://org-id.guide/_preview_branch/PL-REGON](http://org-id.guide/_preview_branch/PL-REGON)  (visiting [http://org-id.guide/list/PL-REGON](http://org-id.guide/list/PL-REGON) when the preview is active or check the files changed options above.

New  registry entry for 'REGON - Statistical number of an economy entity' (PL-REGON)

---

lists/et/et-mot.json

A new list has been proposed with the code ET-MOT
**List title:** Ministry of Trade (Ethiopia)
Preview the platform with this list at [http://org-id.guide/_preview_branch/ET-MOT](http://org-id.guide/_preview_branch/ET-MOT)  (visiting [http://org-id.guide/list/ET-MOT](http://org-id.guide/list/ET-MOT) when the preview is active or check the files changed options above.

New  registry entry for 'Ministry of Trade (Ethiopia)' (ET-MOT)

---

lists/xm/xm-dac.json

An update to the list with code XM-DAC has been proposed
**List title:** OECD Development Assistance Committee
Preview the platform with this list at [http://org-id.guide/_preview_branch/XM-DAC](http://org-id.guide/_preview_branch/XM-DAC)  (visiting [http://org-id.guide/list/XM-DAC](http://org-id.guide/list/XM-DAC) when the preview is active or check the files changed options above.

Updated  registry entry for 'OECD Development Assistance Committee' (XM-DAC)

---

lists/ar/ar-cenoc.json

A new list has been proposed with the code AR-CENOC
**List title:** The National Centre of Community Organisations (Argentina)
Preview the platform with this list at [http://org-id.guide/_preview_branch/AR-CENOC](http://org-id.guide/_preview_branch/AR-CENOC)  (visiting [http://org-id.guide/list/AR-CENOC](http://org-id.guide/list/AR-CENOC) when the preview is active or check the files changed options above.

New  registry entry for 'The National Centre of Community Organisations (Argentina)' (AR-CENOC)

---

lists/ph/ph-sec.json

A new list has been proposed with the code PH-SEC
**List title:** Securities and Exchange Commission (Philippines)
Preview the platform with this list at [http://org-id.guide/_preview_branch/PH-SEC](http://org-id.guide/_preview_branch/PH-SEC)  (visiting [http://org-id.guide/list/PH-SEC](http://org-id.guide/list/PH-SEC) when the preview is active or check the files changed options above.

New  registry entry for 'Securities and Exchange Commission (Philippines)' (PH-SEC)

---

lists/tr/tr-moi.json

A new list has been proposed with the code TR-MOI
**List title:** Department of Associations (Ministry of Interior, Turkey)
Preview the platform with this list at [http://org-id.guide/_preview_branch/TR-MOI](http://org-id.guide/_preview_branch/TR-MOI)  (visiting [http://org-id.guide/list/TR-MOI](http://org-id.guide/list/TR-MOI) when the preview is active or check the files changed options above.

New  registry entry for 'Department of Associations (Ministry of Interior, Turkey)' (TR-MOI)

---

lists/bw/bw-cipa.json

A new list has been proposed with the code BW-CIPA
**List title:** Companies and Intellectual Property Authority (Botswana)
Preview the platform with this list at [http://org-id.guide/_preview_branch/BW-CIPA](http://org-id.guide/_preview_branch/BW-CIPA)  (visiting [http://org-id.guide/list/BW-CIPA](http://org-id.guide/list/BW-CIPA) when the preview is active or check the files changed options above.

New  registry entry for 'Companies and Intellectual Property Authority (Botswana)' (BW-CIPA)

---

lists/ch/ch-fdjp.json

A new list has been proposed with the code CH-FDJP
**List title:** Commercial Registry, Federal Office of Justice (Switzerland)
Preview the platform with this list at [http://org-id.guide/_preview_branch/CH-FDJP](http://org-id.guide/_preview_branch/CH-FDJP)  (visiting [http://org-id.guide/list/CH-FDJP](http://org-id.guide/list/CH-FDJP) when the preview is active or check the files changed options above.

New  registry entry for 'Commercial Registry, Federal Office of Justice (Switzerland)' (CH-FDJP)

---

lists/ss/ss-rrc.json

A new list has been proposed with the code SS-RRC
**List title:** South Sudan Relief and Rehabilitation Commission
Preview the platform with this list at [http://org-id.guide/_preview_branch/SS-RRC](http://org-id.guide/_preview_branch/SS-RRC)  (visiting [http://org-id.guide/list/SS-RRC](http://org-id.guide/list/SS-RRC) when the preview is active or check the files changed options above.

New  registry entry for 'South Sudan Relief and Rehabilitation Commission' (SS-RRC)

---

lists/lb/lb-moi.json

A new list has been proposed with the code LB-MOI
**List title:** Ministry of Interior (Lebanon)
Preview the platform with this list at [http://org-id.guide/_preview_branch/LB-MOI](http://org-id.guide/_preview_branch/LB-MOI)  (visiting [http://org-id.guide/list/LB-MOI](http://org-id.guide/list/LB-MOI) when the preview is active or check the files changed options above.

New  registry entry for 'Ministry of Interior (Lebanon)' (LB-MOI)

---

lists/ml/ml-ccim.json

A new list has been proposed with the code ML-CCIM
**List title:** The Chamber of Commerce and Industry of Mali
Preview the platform with this list at [http://org-id.guide/_preview_branch/ML-CCIM](http://org-id.guide/_preview_branch/ML-CCIM)  (visiting [http://org-id.guide/list/ML-CCIM](http://org-id.guide/list/ML-CCIM) when the preview is active or check the files changed options above.

New  registry entry for 'The Chamber of Commerce and Industry of Mali' (ML-CCIM)

---

lists/se/se-kk.json

A new list has been proposed with the code SE-KK
**List title:** Legal, Financial and Administrative Services Agency (Sweden)
Preview the platform with this list at [http://org-id.guide/_preview_branch/SE-KK](http://org-id.guide/_preview_branch/SE-KK)  (visiting [http://org-id.guide/list/SE-KK](http://org-id.guide/list/SE-KK) when the preview is active or check the files changed options above.

New  registry entry for 'Legal, Financial and Administrative Services Agency (Sweden)' (SE-KK)

---

lists/xi/xi-eori.json

A new list has been proposed with the code XI-EORI
**List title:** Economic Operators Identification and Registration system
Preview the platform with this list at [http://org-id.guide/_preview_branch/XI-EORI](http://org-id.guide/_preview_branch/XI-EORI)  (visiting [http://org-id.guide/list/XI-EORI](http://org-id.guide/list/XI-EORI) when the preview is active or check the files changed options above.

New  registry entry for 'Economic Operators Identification and Registration system' (XI-EORI)

---

lists/gb/gb-nic.json

I've added some more information to update the entry for `GB-NIC`.
Strictly speaking, the `name` is the name of register maintaining body (Charity Commission NI) rather than the name of list itself, but 
So, I've left it but it might be better to swap the `en` and `local` values to:
"name": {
"en": "Northern Ireland Register of Charities",
"local": "The Charity Commission for Northern Ireland"
}

Northern Ireland Charity Register

---

lists/gb/gb-nic.json

An update to the list with code GB-NIC has been proposed
List title: The Charity Commission for Northern Ireland
Preview the platform with this list at http://org-id.guide/_preview_branch/GB-NIC (visiting http://org-id.guide/list/GB-NIC when the preview is active or check the files changed options above.
Unless objections are raised, this update will be merged after 3 days.

List update: GB-NIC - The Charity Commission for Northern Ireland

---

lists/it/it-cf.json
lists/it/it-ri.json

Looking for a registration number/identifier to use for INGO based in Italy, we found the AICS register of civil society organisations, which can be identified by their Codice Fiscale (Tax number, also their VAT Number).
This describes where the CF can be found, deprecating the IT-RI list as this also describes the 'Registro Imprese': both lists use the CF as the identifier.
(Internal ticket #11117)

IT-CF: Italy Codice Fiscale (Tax number)

---

lists/it/it-cf.json

A new list has been proposed with the code IT-CF
**List title**: Codice Fiscale (Italy)
Preview the platform with this list at http://org-id.guide/_preview_branch/IT-CF (visiting http://org-id.guide/list/IT-CF when the preview is active or check the files changed options above.

New list for Italy - Codice Fiscale IT-CF

---

lists/xi/xi-pid.json

A new list has been proposed with the code XI-PID
**List title:** PermID: Thompson Reuters Permanent Identifier
Preview the platform with this list at [http://org-id.guide/_preview_branch/XI-PID](http://org-id.guide/_preview_branch/XI-PID)  (visiting [http://org-id.guide/list/XI-PID](http://org-id.guide/list/XI-PID) when the preview is active or check the files changed options above.

New  registry entry for 'PermID: Thompson Reuters Permanent Identifier' (XI-PID)

---

lists/ge/ge-napr.json

A new list has been proposed with the code GE-NAPR
**List title:** Register of Entrepreneurial and Non-Entrepreneurial Legal Entities, Georgia
Preview the platform with this list at [http://org-id.guide/_preview_branch/GE-NAPR](http://org-id.guide/_preview_branch/GE-NAPR)  (visiting [http://org-id.guide/list/GE-NAPR](http://org-id.guide/list/GE-NAPR) when the preview is active or check the files changed options above.

New  registry entry for 'Register of Entrepreneurial and Non-Entrepreneurial Legal Entities, Georgia' (GE-NAPR)

---

lists/et/et-csa.json

A new list has been proposed with the code ET-CSA after a request from an IATI publisher (#76) 
**List title**:  Charities and Societies Agency (Ethiopia)
Preview the org-id.guide platform with this list at http://org-id.guide/_preview_branch/ET-CSA (visiting http://org-id.guide/list/ET-CSA when the preview is active or check the files changed options above.
_Please note that the registration list is not accessible online._

[Proposed] ET-CSA Charities and Societies Agency (Ethiopia) #76

---

lists/id/id-kln.json

An update to the list with code ID-KLN has been proposed
**List title:** Ministry of Foreign affairs
Removing artefacts from the research process (reference to OIPA. See #80)
Preview the platform with this list at [http://org-id.guide/_preview_branch/ID-KLN](http://org-id.guide/_preview_branch/ID-KLN)  (visiting [http://org-id.guide/list/ID-KLN](http://org-id.guide/list/ID-KLN) when the preview is active or check the files changed options above.

Updated  registry entry for 'Ministry of Foreign affairs' (ID-KLN)

---

lists/sn/sn-ninea.json

A new list has been proposed with the code SN-NINEA
**List title:** National Identification Number of Companies and Associations (Senegal)
Adding SN-NINEA list (Senegal)
Preview the platform with this list at [http://org-id.guide/_preview_branch/SN-NINEA](http://org-id.guide/_preview_branch/SN-NINEA)  (visiting [http://org-id.guide/list/SN-NINEA](http://org-id.guide/list/SN-NINEA) when the preview is active or check the files changed options above.

New  registry entry for 'National Identification Number of Companies and Associations (Senegal)' (SN-NINEA)

---

lists/mz/mz-moj.json

An update to the list with code MZ-MOJ has been proposed
**List title:** Mozambique Ministry of Justice
Preview the platform with this list at [http://org-id.guide/_preview_branch/MZ-MOJ](http://org-id.guide/_preview_branch/MZ-MOJ)  (visiting [http://org-id.guide/list/MZ-MOJ](http://org-id.guide/list/MZ-MOJ) when the preview is active or check the files changed options above.

Updated  registry entry for 'Mozambique Ministry of Justice' (MZ-MOJ)

---

lists/mx/mx-rfc.json

A new list has been proposed with the code MX-RFC
**List title:** Federal Taxpayers Registry
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/MX-RFC](http://org-id.guide/_preview_branch/MX-RFC)  (visiting [http://org-id.guide/list/MX-RFC](http://org-id.guide/list/MX-RFC) when the preview is active or check the files changed options above.

New  registry entry for 'Federal Taxpayers Registry' (MX-RFC)

---

lists/mx/mx-cpa.json

A new list has been proposed with the code MX-CPA
**List title:** Budget Classification of Public Entities (Mexico)
As discussed in #81
Preview the platform with this list at [http://org-id.guide/_preview_branch/MX-CPA](http://org-id.guide/_preview_branch/MX-CPA)  (visiting [http://org-id.guide/list/MX-CPA](http://org-id.guide/list/MX-CPA) when the preview is active or check the files changed options above.

New  registry entry for 'Budget Classification of Public Entities (Mexico)' (MX-CPA)

---

lists/gb/gb-shpe.json

A new list has been proposed with the code GB-SHPE
**List title:** Registered Social Housing Providers (England)
initial proposal for social housing providers
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-SHPE](http://org-id.guide/_preview_branch/GB-SHPE)  (visiting [http://org-id.guide/list/GB-SHPE](http://org-id.guide/list/GB-SHPE) when the preview is active or check the files changed options above.

New  registry entry for 'Registered Social Housing Providers (England)' (GB-SHPE)

---

lists/si/si-tin.json

A new list has been proposed with the code SI-TIN
**List title:** Tax Identification Number (Slovenia)
Preview the platform with this list at [http://org-id.guide/_preview_branch/SI-TIN](http://org-id.guide/_preview_branch/SI-TIN)  (visiting [http://org-id.guide/list/SI-TIN](http://org-id.guide/list/SI-TIN) when the preview is active or check the files changed options above.

New  registry entry for 'Tax Identification Number (Slovenia)' (SI-TIN)

---

lists/lv/lv-re.json

An update to the list with code LV-RE has been proposed
**List title:** Register of Enterprises of the Republic of Latvia
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/LV-RE](http://org-id.guide/_preview_branch/LV-RE)  (visiting [http://org-id.guide/list/LV-RE](http://org-id.guide/list/LV-RE) when the preview is active or check the files changed options above.

Updated  registry entry for 'Register of Enterprises of the Republic of Latvia' (LV-RE)

---

lists/jp/jp-jcn.json

A new list has been proposed with the code JP-JCN
**List title:** National Tax Agency Corporate Number Publication Site
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/JP-JCN](http://org-id.guide/_preview_branch/JP-JCN)  (visiting [http://org-id.guide/list/JP-JCN](http://org-id.guide/list/JP-JCN) when the preview is active or check the files changed options above.

New  registry entry for 'National Tax Agency Corporate Number Publication Site' (JP-JCN)

---

lists/si/si-prs.json

A new list has been proposed with the code SI-PRS
**List title:** Slovenian Business Register
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/SI-PRS](http://org-id.guide/_preview_branch/SI-PRS)  (visiting [http://org-id.guide/list/SI-PRS](http://org-id.guide/list/SI-PRS) when the preview is active or check the files changed options above.

New  registry entry for 'Slovenian Business Register' (SI-PRS)

---

lists/at/at-uid.json

A new list has been proposed with the code AT-UID
**List title:** VAT number (Austria Company Register)
vat number - reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AT-UID](http://org-id.guide/_preview_branch/AT-UID)  (visiting [http://org-id.guide/list/AT-UID](http://org-id.guide/list/AT-UID) when the preview is active or check the files changed options above.

New  registry entry for 'VAT number (Austria Company Register)' (AT-UID)

---

lists/gb/gb-irn.json

A new list has been proposed with the code GB-IRN
**List title:** Schools Plus, Department of Education (Northern Ireland)
list for northern ireland schools
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-IRN](http://org-id.guide/_preview_branch/GB-IRN)  (visiting [http://org-id.guide/list/GB-IRN](http://org-id.guide/list/GB-IRN) when the preview is active or check the files changed options above.

New  registry entry for 'Schools Plus, Department of Education (Northern Ireland)' (GB-IRN)

---

lists/lt/lt-pvm.json

A new list has been proposed with the code LT-PVM
**List title:** Lithuania Register of Legal Entities
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/LT-PVM](http://org-id.guide/_preview_branch/LT-PVM)  (visiting [http://org-id.guide/list/LT-PVM](http://org-id.guide/list/LT-PVM) when the preview is active or check the files changed options above.

New  registry entry for 'Lithuania Register of Legal Entities' (LT-PVM)

---

lists/az/az-ivi.json

A new list has been proposed with the code AZ-IVI
**List title:** State Register of Commercial Entities (Ministry of Taxes of Azerbaijan Republic)
reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AZ-IVI](http://org-id.guide/_preview_branch/AZ-IVI)  (visiting [http://org-id.guide/list/AZ-IVI](http://org-id.guide/list/AZ-IVI) when the preview is active or check the files changed options above.

New  registry entry for 'State Register of Commercial Entities (Ministry of Taxes of Azerbaijan Republic)' (AZ-IVI)

---

lists/lt/lt-rc.json

A new list has been proposed with the code LT-RC
**List title:** Information Platform of Legal Entities (Lithuania)
reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/LT-RC](http://org-id.guide/_preview_branch/LT-RC)  (visiting [http://org-id.guide/list/LT-RC](http://org-id.guide/list/LT-RC) when the preview is active or check the files changed options above.

New registry entry for 'Information Platform of Legal Entities (Lithuania)' (LT-RC)

---

lists/ru/ru-ogrn.json

A new list has been proposed with the code RU-OGRN
**List title:** Unified State Register of Legal Entities (USRLE), Russian Federation
review and update
Preview the platform with this list at [http://org-id.guide/_preview_branch/RU-OGRN](http://org-id.guide/_preview_branch/RU-OGRN)  (visiting [http://org-id.guide/list/RU-OGRN](http://org-id.guide/list/RU-OGRN) when the preview is active or check the files changed options above.

New  registry entry for 'Unified State Register of Legal Entities (USRLE), Russian Federation' (RU-OGRN)

---

lists/ro/ro-cui.json

A new list has been proposed with the code RO-CUI
**List title:** National Trade Register (Romania)
review and updated
Preview the platform with this list at [http://org-id.guide/_preview_branch/RO-CUI](http://org-id.guide/_preview_branch/RO-CUI)  (visiting [http://org-id.guide/list/RO-CUI](http://org-id.guide/list/RO-CUI) when the preview is active or check the files changed options above.

New  registry entry for 'National Trade Register (Romania)' (RO-CUI)

---

lists/es/es-rmc.json

A new list has been proposed with the code ES-RMC
**List title:** Central Commercial Register of the Kingdom of Spain
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/ES-RMC](http://org-id.guide/_preview_branch/ES-RMC)  (visiting [http://org-id.guide/list/ES-RMC](http://org-id.guide/list/ES-RMC) when the preview is active or check the files changed options above.

New  registry entry for 'Central Commercial Register of the Kingdom of Spain' (ES-RMC)

---

lists/cy/cy-drcor.json

A new list has been proposed with the code CY-DRCOR
**List title:** Cyprus Department of Registrar of Companies and Official Receiver (DRCOR)
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/CY-DRCOR](http://org-id.guide/_preview_branch/CY-DRCOR)  (visiting [http://org-id.guide/list/CY-DRCOR](http://org-id.guide/list/CY-DRCOR) when the preview is active or check the files changed options above.

New  registry entry for 'Cyprus Department of Registrar of Companies and Official Receiver (DRCOR)' (CY-DRCOR)

---

lists/mz/mz-nuit.json

A new list has been proposed with the code MZ-NUIT
**List title:** Taxpayer Single Identification Number (Mozambique)
Created to address #129 
Preview the platform with this list at [http://org-id.guide/_preview_branch/MZ-NUIT](http://org-id.guide/_preview_branch/MZ-NUIT)  (visiting [http://org-id.guide/list/MZ-NUIT](http://org-id.guide/list/MZ-NUIT) when the preview is active or check the files changed options above.

New  registry entry for 'Taxpayer Single Identification Number (Mozambique)' (MZ-NUIT)

---

lists/zw/zw-pvo.json

A new list has been proposed with the code ZW-PVO
**List title:** Private Voluntary Organisations Council (Zimbabwe)
This list was originally in the IATI Organization Registration Agency. It appears it was missed during the go-live of org-id.guide, so this updates the meta-data for it and sets it to live.
Preview the platform with this list at [http://org-id.guide/_preview_branch/ZW-PVO](http://org-id.guide/_preview_branch/ZW-PVO)  (visiting [http://org-id.guide/list/ZW-PVO](http://org-id.guide/list/ZW-PVO) when the preview is active or check the files changed options above.

New  registry entry for 'Private Voluntary Organisations Council (Zimbabwe)' (ZW-PVO)

---

lists/ca/ca-gov.json

A new list has been proposed with the code CA-GOV
**List title:** List of legal department names (Government of Canada)
Adding the list used by Public Works Canada, and currently being promoted for use across Canadian Government. 
Preview the platform with this list at [http://org-id.guide/_preview_branch/CA-GOV](http://org-id.guide/_preview_branch/CA-GOV)  (visiting [http://org-id.guide/list/CA-GOV](http://org-id.guide/list/CA-GOV) when the preview is active or check the files changed options above.

New  registry entry for 'List of legal department names (Government of Canada)' (CA-GOV)

---

lists/se/se-blv.json
lists/se/se-kk.json
lists/se/se-on.json

A new list has been proposed with the code SE-ON
**List title:** Business Registration Number (Organisationsnummer), Sweden
addition of SE-ON, deprecation of SE-KK and SE-BLV
Preview the platform with this list at [http://org-id.guide/_preview_branch/SE-ON](http://org-id.guide/_preview_branch/SE-ON)  (visiting [http://org-id.guide/list/SE-ON](http://org-id.guide/list/SE-ON) when the preview is active or check the files changed options above.

New  registry entry for 'Business Registration Number (Organisationsnummer), Sweden' (SE-ON)

---

lists/gb/gb-edu.json

An update to the list with code GB-EDU has been proposed
**List title:** Register of Schools (England and Wales)
new home and register for former Edubase
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-EDU](http://org-id.guide/_preview_branch/GB-EDU)  (visiting [http://org-id.guide/list/GB-EDU](http://org-id.guide/list/GB-EDU) when the preview is active or check the files changed options above.

Updated  registry entry for 'Register of Schools (England and Wales)' (GB-EDU)

---

lists/gb/gb-nic.json

An update to the list with code GB-NIC has been proposed
**List title:** The Charity Commission for Northern Ireland
fix examples string
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-NIC](http://org-id.guide/_preview_branch/GB-NIC)  (visiting [http://org-id.guide/list/GB-NIC](http://org-id.guide/list/GB-NIC) when the preview is active or check the files changed options above.

Updated  registry entry for 'The Charity Commission for Northern Ireland' (GB-NIC)

---

lists/gb/gb-nhs.json

A new list has been proposed with the code GB-NHS
**List title:** NHS Digital - Organisation Data Service
addition of GB-NHS #184 
~Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-NHS](http://org-id.guide/_preview_branch/GB-NHS)  (visiting [http://org-id.guide/list/GB-NHS](http://org-id.guide/list/GB-NHS) when the preview is active~ or check the files changed options above.

New  registry entry for 'NHS Digital - Organisation Data Service' (GB-NHS)

---

lists/xi/xi-grid.json

A new list has been proposed with the code XI-GRID
List title: Global Research Identifier Database
Preview the platform with this list at http://dev.org-id.guide/_preview_branch/XI-GRID (visiting http://dev.org-id.guide/list/XI-GRID when the preview is active or check the files changed options above.

New registry entry for 'Global Research Identifier Database' (XI-GRID)

---

lists/rw/rw-rgb.json

A new list has been proposed with the code RW-RGB
**List title:** Rwanda Governance Board
See https://github.com/org-id/register/issues/213
Preview the platform with this list at [http://org-id.guide/_preview_branch/RW-RGB](http://org-id.guide/_preview_branch/RW-RGB)  (visiting [http://org-id.guide/list/RW-RGB](http://org-id.guide/list/RW-RGB) when the preview is active or check the files changed options above.

New  registry entry for 'Rwanda Governance Board' (RW-RGB)

---

lists/cr/cr-rpj.json

A new list has been proposed with the code CR-RPJ
**List title:** Registro de Personas Jurídicas (Costa Rica)
Addresses #235 
Preview the platform with this list at [http://org-id.guide/_preview_branch/CR-RPJ](http://org-id.guide/_preview_branch/CR-RPJ)  (visiting [http://org-id.guide/list/CR-RPJ](http://org-id.guide/list/CR-RPJ) when the preview is active or check the files changed options above.

New  registry entry for 'Registro de Personas Jurídicas (Costa Rica)' (CR-RPJ)

---

lists/af/af-cbr.json

An update to the list with code AF-CBR has been proposed
**List title:** Afghanistan Central Business Registry
Updates to meta-data - closes #233
Preview the platform with this list at [http://org-id.guide/_preview_branch/AF-CBR](http://org-id.guide/_preview_branch/AF-CBR)  (visiting [http://org-id.guide/list/AF-CBR](http://org-id.guide/list/AF-CBR) when the preview is active or check the files changed options above.

Updated  registry entry for 'Afghanistan Central Business Registry' (AF-CBR)

---

lists/af/af-coa.json

A new list has been proposed with the code AF-COA
**List title:** Afghanistan Chart of Accounts
Staging #234 - closes #234
Preview the platform with this list at [http://org-id.guide/_preview_branch/AF-COA](http://org-id.guide/_preview_branch/AF-COA)  (visiting [http://org-id.guide/list/AF-COA](http://org-id.guide/list/AF-COA) when the preview is active or check the files changed options above.

New  registry entry for 'Afghanistan Chart of Accounts' (AF-COA)

---

lists/bw/bw-tin.json

A new list has been proposed with the code BW-TIN
**List title:** Botswana Taxpayers Identification Number
Staging entry to address #248 - closes #248
Preview the platform with this list at [http://org-id.guide/_preview_branch/BW-TIN](http://org-id.guide/_preview_branch/BW-TIN)  (visiting [http://org-id.guide/list/BW-TIN](http://org-id.guide/list/BW-TIN) when the preview is active or check the files changed options above.

New  registry entry for 'Botswana Taxpayers Identification Number' (BW-TIN)

---

lists/ge/ge-rs.json

A new list has been proposed with the code GE-RS
**List title:** Georgian Revenue Service
Adding Georgian Revenue Service - addresses #259
Preview the platform with this list at [http://org-id.guide/_preview_branch/GE-RS](http://org-id.guide/_preview_branch/GE-RS)  (visiting [http://org-id.guide/list/GE-RS](http://org-id.guide/list/GE-RS) when the preview is active or check the files changed options above.

New  registry entry for 'Georgian Revenue Service' (GE-RS)

---

lists/gb/gb-srs.json

A new list has been proposed with the code GB-SRS
**List title:** Supplier Registration Service, Crown Commercial Service, UK
Adds list as requested in #261
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-SRS](http://org-id.guide/_preview_branch/GB-SRS)  (visiting [http://org-id.guide/list/GB-SRS](http://org-id.guide/list/GB-SRS) when the preview is active or check the files changed options above.

New  registry entry for 'Supplier Registration Service, Crown Commercial Service, UK' (GB-SRS)

---

lists/ye/ye-msal.json

A new list has been proposed with the code YE-MSAL
**List title:** Ministry of Social Affairs and Labour
Addresses #258
Preview the platform with this list at [http://org-id.guide/_preview_branch/YE-MSAL](http://org-id.guide/_preview_branch/YE-MSAL)  (visiting [http://org-id.guide/list/YE-MSAL](http://org-id.guide/list/YE-MSAL) when the preview is active or check the files changed options above.

New  registry entry for 'Ministry of Social Affairs and Labour' (YE-MSAL)

---

lists/ge/ge-napr.json

An update to the list with code GE-NAPR has been proposed
**List title:** Register of Entrepreneurial and Non-Entrepreneurial Legal Entities, Georgia
Minor change in response to #72
Preview the platform with this list at [http://org-id.guide/_preview_branch/GE-NAPR](http://org-id.guide/_preview_branch/GE-NAPR)  (visiting [http://org-id.guide/list/GE-NAPR](http://org-id.guide/list/GE-NAPR) when the preview is active or check the files changed options above.

Updated  registry entry for 'Register of Entrepreneurial and Non-Entrepreneurial Legal Entities, Georgia' (GE-NAPR)

---

lists/gt/gt-cisp.json

A new list has been proposed with the code GT-CISP
**List title:** Public Sector Institution Classifications (Guetmala)
See #268
Preview the platform with this list at [http://org-id.guide/_preview_branch/GT-CISP](http://org-id.guide/_preview_branch/GT-CISP)  (visiting [http://org-id.guide/list/GT-CISP](http://org-id.guide/list/GT-CISP) when the preview is active or check the files changed options above.

New  registry entry for 'Public Sector Institution Classifications (Guetmala)' (GT-CISP)

---

lists/lk/lk-ngo.json

A new list has been proposed with the code LK-NGO
**List title:** Sri Lanka - National Secretariat for Non-Governmental Organisations
Discovered when carrying out research and added based on initial review.
Preview the platform with this list at [http://org-id.guide/_preview_branch/LK-NGO](http://org-id.guide/_preview_branch/LK-NGO)  (visiting [http://org-id.guide/list/LK-NGO](http://org-id.guide/list/LK-NGO) when the preview is active or check the files changed options above.

New  registry entry for 'Sri Lanka - National Secretariat for Non-Governmental Organisations' (LK-NGO)

---

lists/lk/lk-drc.json

A new list has been proposed with the code LK-DRC
**List title:** Department of the Registrar of Companies (Sri Lanka)
Adding LK-DRC in response to support request.
Preview the platform with this list at [http://org-id.guide/_preview_branch/LK-DRC](http://org-id.guide/_preview_branch/LK-DRC)  (visiting [http://org-id.guide/list/LK-DRC](http://org-id.guide/list/LK-DRC) when the preview is active or check the files changed options above.

New  registry entry for 'Department of the Registrar of Companies (Sri Lanka)' (LK-DRC)

---

lists/ug/ug-ngo.json

An update to the list with code UG-NGO has been proposed
**List title:** National Bureau for NGOs (Uganda)
Updating to reflect that NGO register is a secondary status - not primary registration. 
Preview the platform with this list at [http://org-id.guide/_preview_branch/UG-NGO](http://org-id.guide/_preview_branch/UG-NGO)  (visiting [http://org-id.guide/list/UG-NGO](http://org-id.guide/list/UG-NGO) when the preview is active or check the files changed options above.

Updated  registry entry for 'National Bureau for NGOs (Uganda)' (UG-NGO)

---

lists/ug/ug-ngb.json

An update to the list with code UG-NGB has been proposed
**List title:** NGO Board, Ministry of Internal Affairs (Uganda)
I'm proposing deprecation of this list, as it points to the same place as UG-RSB as the source of identifiers, and overlaps with UG-NGO. 
Preview the platform with this list at [http://org-id.guide/_preview_branch/UG-NGB](http://org-id.guide/_preview_branch/UG-NGB)  (visiting [http://org-id.guide/list/UG-NGB](http://org-id.guide/list/UG-NGB) when the preview is active or check the files changed options above.

Updated  registry entry for 'NGO Board, Ministry of Internal Affairs (Uganda)' (UG-NGB)

---

lists/xe/xe-example.json

An update to the list with code XE-EXAMPLE has been proposed
**List title:** Example Data Prefix
demo pull request see #299
Preview the platform with this list at [http://org-id.guide/_preview_branch/XE-EXAMPLE](http://org-id.guide/_preview_branch/XE-EXAMPLE)  (visiting [http://org-id.guide/list/XE-EXAMPLE](http://org-id.guide/list/XE-EXAMPLE) when the preview is active or check the files changed options above.

Updated  registry entry for 'Example Data Prefix' (XE-EXAMPLE)

---

lists/gb/gb-lani.json

A new list has been proposed with the code GB-LANI
**List title:** Local authorities for Northern Ireland register
Local authorities of Northern Ireland - needs to have subnational region added.
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-LANI](http://org-id.guide/_preview_branch/GB-LANI)  (visiting [http://org-id.guide/list/GB-LANI](http://org-id.guide/list/GB-LANI) when the preview is active or check the files changed options above.

New  registry entry for 'Local authorities for Northern Ireland register' (GB-LANI)

---

lists/gh/gh-rgd.json

An update to the list with code GH-RGD has been proposed
**List title:** Registrar General's Department
ad hoc updated date correction
Preview the platform with this list at [http://org-id.guide/_preview_branch/GH-RGD](http://org-id.guide/_preview_branch/GH-RGD)  (visiting [http://org-id.guide/list/GH-RGD](http://org-id.guide/list/GH-RGD) when the preview is active or check the files changed options above.

Updated  registry entry for 'Registrar General's Department' (GH-RGD)

---

lists/ml/ml-mat.json

A new list has been proposed with the code ML-MAT
**List title:** Ministere de l'Administration Territoriale 
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/ML-MAT](http://org-id.guide/_preview_branch/ML-MAT)  (visiting [http://org-id.guide/list/ML-MAT](http://org-id.guide/list/ML-MAT) when the preview is active or check the files changed options above.

New  registry entry for 'Ministere de l'Administration Territoriale ' (ML-MAT)

---

lists/gb/gb-nhs.json

An update to the list with code GB-NHS has been proposed
**List title:** NHS Digital - Organisation Data Service
update to include new search facility
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-NHS](http://org-id.guide/_preview_branch/GB-NHS)  (visiting [http://org-id.guide/list/GB-NHS](http://org-id.guide/list/GB-NHS) when the preview is active or check the files changed options above.

Updated  registry entry for 'NHS Digital - Organisation Data Service' (GB-NHS)

---

lists/sl/sl-nra.json

A new list has been proposed with the code SL-NRA
**List title:** National Revenue Agency
Preview the platform with this list at [http://org-id.guide/_preview_branch/SL-NRA](http://org-id.guide/_preview_branch/SL-NRA)  (visiting [http://org-id.guide/list/SL-NRA](http://org-id.guide/list/SL-NRA) when the preview is active or check the files changed options above.

New  registry entry for 'National Revenue Agency' (SL-NRA)

---

lists/al/al-qkb.json

Editing the file directly in the org-id repo rather than using the vagrantised org-ids option. This is intended to implement #298

Editing file to correct for confirmed: true

---

lists/gb/gb-hesa.json

A new list has been proposed with the code GB-HESA
**List title:** Higher Education Statistics Agency
Addesses issue #358
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-HESA](http://org-id.guide/_preview_branch/GB-HESA)  (visiting [http://org-id.guide/list/GB-HESA](http://org-id.guide/list/GB-HESA) when the preview is active or check the files changed options above.

New  registry entry for 'Higher Education Statistics Agency' (GB-HESA)

---

lists/gb/gb-casc.json

A new list has been proposed with the code GB-CASC
**List title:** Community amateur sports clubs (CASCs) registered with HMRC
Addresses proposal #361
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-CASC](http://org-id.guide/_preview_branch/GB-CASC)  (visiting [http://org-id.guide/list/GB-CASC](http://org-id.guide/list/GB-CASC) when the preview is active or check the files changed options above.

New  registry entry for 'Community amateur sports clubs (CASCs) registered with HMRC' (GB-CASC)

---

lists/xi/xi-ror.json

A new list has been proposed with the code XI-ROR
**List title:** Research Organization Registry
Added XI-ROR
Preview the platform with this list at [http://org-id.guide/_preview_branch/XI-ROR](http://org-id.guide/_preview_branch/XI-ROR)  (visiting [http://org-id.guide/list/XI-ROR](http://org-id.guide/list/XI-ROR) when the preview is active or check the files changed options above.

New  registry entry for 'Research Organization Registry' (XI-ROR)

---

lists/je/je-jcr.json

A new list has been proposed with the code JE-JCR
**List title:** Jersey Charity Register
Added JE-JCR
Preview the platform with this list at [http://org-id.guide/_preview_branch/JE-JCR](http://org-id.guide/_preview_branch/JE-JCR)  (visiting [http://org-id.guide/list/JE-JCR](http://org-id.guide/list/JE-JCR) when the preview is active or check the files changed options above.

New  registry entry for 'Jersey Charity Register' (JE-JCR)

---

lists/cn/cn-usci.json

This list was researched by @theaschepers.
China's USCIs are universally applied to both domestic and non-domestic actors who are economically or socially active in China. They can be minted by several agencies, though. And there doesn't appear to be a single agency that has a searchable database of USCIs across sectors; hence the various platforms and URLs presented in the list details.

Create cn-usci.json closes #363

---

lists/gt/gt-nit.json

A new list has been proposed with the code GT-NIT
**List title:** Guatemala Tax Identification Number
add draft GT-NIT list
Preview the platform with this list at [http://org-id.guide/_preview_branch/GT-NIT](http://org-id.guide/_preview_branch/GT-NIT)  (visiting [http://org-id.guide/list/GT-NIT](http://org-id.guide/list/GT-NIT) when the preview is active or check the files changed options above.
Some further information is required before the list can be merged.

New  registry entry for 'Guatemala Tax Identification Number' (GT-NIT)

---

lists/zz/zz-ebid.json

This is one of the registers listed on iso 6523 that we're adding. See open-contracting/standard#987
This list appears to cover both Austrian and German companies. I've therefore followed the advice in the [org-id handbook](http://docs.org-id.guide/en/latest/metadata/#assigning-a-code) and issued it a 'zz'-based prefix.

Create zz-ebid.json - fixes #434

---

lists/xi/xi-duns.json

Create xi-duns.json - closes #318

---

lists/br/br-cnpj.json

The [BR-CNPJ](https://org-id.guide/list/BR-CNPJ) list incorrectly links to a third party website as if it was the primary, official source. This PR intends to fix that.
[Receita Federal](https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj)
Note (1): the official link keeps changing quite often. Furthermore, Receita Federal, when asked about it, has consistently refused to put it on the official open data portal ([dados.gov.br](https://dados.gov.br)). We keep track of the official link over the years in this [forum post](https://dadosabertos.social/t/dados-relacionados-a-base-do-cnpj-liberados-pela-receita-federal-do-brasil/23) (in Portuguese language).
Note (2): the official files are in a zipped csv format, but they are very …

Fix BR-CNPJ which incorrectly points to a third party website

---

lists/ch/ch-bs-cr.json

This change is in response to the [comment and exchange](https://github.com/org-id/register/pull/502#issuecomment-1103707920) on a recent merged PR.
This would go alongside a [change](https://github.com/org-id/handbook/pull/25) to the handbook guidance, to introduce some consistency.

Replacing hypen with underscore in CH-BS-CR org list code

---

lists/so/so-mpnd.json

Fix #536 
- The Ministry of Planning urls on the org-id SO-MPND page have been updated (the old domain has been taken over and these links are no longer safe). 
- Old urls have been removed or replaced in the description 
- An example SO-MPND identifier has been added.

Fix #536 - Update SO-MPND urls

---

lists/bf/bf-coa.json
lists/bj/bj-coa.json
lists/bw/bw-coa.json
lists/cf/cf-coa.json
lists/cg/cg-coa.json
lists/ci/ci-coa.json
lists/cm/cm-coa.json
lists/et/et-coa.json
lists/gh/gh-coa.json
lists/gm/gm-coa.json
lists/gq/gq-coa.json
lists/gw/gw-coa.json
lists/ke/ke-coa.json
lists/kg/kg-coa.json
lists/kh/kh-coa.json
lists/kn/kn-coa.json
lists/ma/ma-coa.json
lists/mg/mg-coa.json
lists/mw/mw-coa.json
lists/na/na-coa.json
lists/ng/ng-coa.json
lists/nl/nl-coa.json
lists/ph/ph-coa.json
lists/rw/rw-coa.json
lists/sz/sz-coa.json
lists/tj/tj-coa.json
lists/tr/tr-coa.json
lists/tz/tz-coa.json
lists/za/za-coa.json
lists/zm/zm-coa.json

Updates to COA codelists from [Gov ID Finder](https://gov-id-finder.codeforiati.org/)
Includes:
* Updates to a range of codes to ensure they include leading zeroes, where relevant
* Removal of whitespace before and after codes
* Added codes for: Benin, Botswana, Congo (Rep.), Equatorial Guinea, Morocco, Namibia, Nigeria, Philippines, Swaziland, South Africa
* Removed codes for: Cambodia, Kyrgyzstan, Tajikistan - these are not available on gov-id-finder because there were issues with the source data
* Names of Netherlands and Turkey have been updated

2024 Updates from gov-id-finder

---

lists/ar/ar-cuit.json

Change description from 9 to 8 digits
This PR updates the description of the **CUIT** (Unique Tax Identification Code) format for Argentina in our documentation. The previous description incorrectly stated that the **CUIT** contains nine digits in the middle section. The correct format is:
- Two digits (prefix indicating the entity type)
- Hyphen
- Eight digits (unique identification number)
- Hyphen
- One digit (checksum)
- Example: `XX-XXXXXXXX-X`
This change ensures accuracy in the documentation and aligns with Argentina's **official CUIT format.**

Corrected CUIT Format Description: ar-cuit.json

---

lists/xi/xi-grid.json

Fixes #604
- List has been deprecated
- Description has been updated to say it is deprecated
- Errors related to "null" values have been fixed
- Invalid values elsewhere have been removed or updated to avoid syntax errors
- Availability online has been updated to say downloads are only available to Sep 2021
- Coverage has been changed to "XI" to prevent over-dominance in searches

Update xi-grid - fixes #604
