lists/ps/ps-moi.json
A new list has been proposed with the code PS-MOI
**List title:** Ministry of Interior (Palestine)
Preview the platform with this list at [http://org-id.guide/_preview_branch/PS-MOI](http://org-id.guide/_preview_branch/PS-MOI)  (visiting [http://org-id.guide/list/PS-MOI](http://org-id.guide/list/PS-MOI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ministry of Interior (Palestine)' (PS-MOI)

lists/hk/hk-cr.json
A new list has been proposed with the code HK-CR
**List title:** Hong Kong Companies Register
Preview the platform with this list at [http://org-id.guide/_preview_branch/HK-CR](http://org-id.guide/_preview_branch/HK-CR)  (visiting [http://org-id.guide/list/HK-CR](http://org-id.guide/list/HK-CR) when the preview is active or check the files changed options above.
=> New  registry entry for 'Hong Kong Companies Register' (HK-CR)

lists/in/in-mha.json
A new list has been proposed with the code IN-MHA
**List title:** Ministry of Home Affairs (India) Foreign Contributions (Regulation) Act Register
Preview the platform with this list at [http://org-id.guide/_preview_branch/IN-MHA](http://org-id.guide/_preview_branch/IN-MHA)  (visiting [http://org-id.guide/list/IN-MHA](http://org-id.guide/list/IN-MHA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ministry of Home Affairs (India) Foreign Contributions (Regulation) Act Register' (IN-MHA)

lists/pl/pl-nip.json
A new list has been proposed with the code PL-NIP
**List title:** Tax Identification Number (Poland)
Preview the platform with this list at [http://org-id.guide/_preview_branch/PL-NIP](http://org-id.guide/_preview_branch/PL-NIP)  (visiting [http://org-id.guide/list/PL-NIP](http://org-id.guide/list/PL-NIP) when the preview is active or check the files changed options above.
=> New  registry entry for 'Tax Identification Number (Poland)' (PL-NIP)

lists/eg/eg-moss.json
A new list has been proposed with the code EG-MOSS
**List title:** Ministry of Social Solidarity and Justice (Egypt)
Preview the platform with this list at [http://org-id.guide/_preview_branch/EG-MOSS](http://org-id.guide/_preview_branch/EG-MOSS)  (visiting [http://org-id.guide/list/EG-MOSS](http://org-id.guide/list/EG-MOSS) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ministry of Social Solidarity and Justice (Egypt)' (EG-MOSS)

lists/id/id-khh.json
A new list has been proposed with the code ID-KHH
**List title:** Ministry of Justice & Human Rights
Preview the platform with this list at [http://org-id.guide/_preview_branch/ID-KHH](http://org-id.guide/_preview_branch/ID-KHH)  (visiting [http://org-id.guide/list/ID-KHH](http://org-id.guide/list/ID-KHH) when the preview is active or check the files changed options above.
=> Updated registry entry for 'Ministry of Justice & Human Rights' (ID-KHH)

lists/im/im-cr.json
A new list has been proposed with the code IM-CR
**List title:** Isle of Man Companies Registry
Preview the platform with this list at [http://org-id.guide/_preview_branch/IM-CR](http://org-id.guide/_preview_branch/IM-CR)  (visiting [http://org-id.guide/list/IM-CR](http://org-id.guide/list/IM-CR) when the preview is active or check the files changed options above.
=> New  registry entry for 'Isle of Man Companies Registry' (IM-CR)

lists/je/je-fsc.json
An update to the list with code JE-FSC has been proposed
**List title:** Jersey Financial Services Commission (JFSC)
Preview the platform with this list at [http://org-id.guide/_preview_branch/JE-FSC](http://org-id.guide/_preview_branch/JE-FSC)  (visiting [http://org-id.guide/list/JE-FSC](http://org-id.guide/list/JE-FSC) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Jersey Financial Services Commission (JFSC)' (JE-FSC)

lists/mz/mz-moj.json
A new list has been proposed with the code MZ-MOJ
**List title:** Mozambique Ministry of Justice
Preview the platform with this list at [http://org-id.guide/_preview_branch/MZ-MOJ](http://org-id.guide/_preview_branch/MZ-MOJ)  (visiting [http://org-id.guide/list/MZ-MOJ](http://org-id.guide/list/MZ-MOJ) when the preview is active or check the files changed options above.
=> New  registry entry for 'Mozambique Ministry of Justice' (MZ-MOJ)

lists/gb/gb-coh.json
An update to the list with code GB-COH has been proposed
**List title:** Companies House
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-COH](http://org-id.guide/_preview_branch/GB-COH)  (visiting [http://org-id.guide/list/GB-COH](http://org-id.guide/list/GB-COH) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Companies House' (GB-COH)

lists/gb/gb-chc.json
An update to the list with code GB-CHC has been proposed
**List title:** Charity Commission
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-CHC](http://org-id.guide/_preview_branch/GB-CHC)  (visiting [http://org-id.guide/list/GB-CHC](http://org-id.guide/list/GB-CHC) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Charity Commission' (GB-CHC)

lists/jo/jo-ccd.json
A new list has been proposed with the code JO-CCD
**List title:** Companies Control Department (Jordan)
Preview the platform with this list at [http://org-id.guide/_preview_branch/JO-CCD](http://org-id.guide/_preview_branch/JO-CCD)  (visiting [http://org-id.guide/list/JO-CCD](http://org-id.guide/list/JO-CCD) when the preview is active or check the files changed options above.
=> New  registry entry for 'Companies Control Department (Jordan)' (JO-CCD)

lists/us/us-ein.json
An update to the list with code US-EIN has been proposed
**List title:** Employer Identification Number - Internal Revenue Service
Preview the platform with this list at [http://org-id.guide/_preview_branch/US-EIN](http://org-id.guide/_preview_branch/US-EIN)  (visiting [http://org-id.guide/list/US-EIN](http://org-id.guide/list/US-EIN) when the preview is active or check the files changed options above.
Unless objections are raised, this update will be merged after 3 days.
=> Updated  registry entry for 'Employer Identification Number - Internal Revenue Service' (US-EIN)

lists/gg/gg-rce.json
An update to the list with code GG-RCE has been proposed
**List title:** Guernsey Registry
Removing artefacts of the research process (references to OIPA, see #80)
Preview the platform with this list at [http://org-id.guide/_preview_branch/GG-RCE](http://org-id.guide/_preview_branch/GG-RCE)  (visiting [http://org-id.guide/list/GG-RCE](http://org-id.guide/list/GG-RCE) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Guernsey Registry' (GG-RCE)

lists/nl/nl-kvk.json
An update to the list with code NL-KVK has been proposed
**List title:** Chamber of Commerce (Netherlands)
minor updates only
Preview the platform with this list at [http://org-id.guide/_preview_branch/NL-KVK](http://org-id.guide/_preview_branch/NL-KVK)  (visiting [http://org-id.guide/list/NL-KVK](http://org-id.guide/list/NL-KVK) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Chamber of Commerce (Netherlands)' (NL-KVK)

lists/mz/mz-cr.json
An update to the list with code MZ-CR has been proposed
**List title:** Mozambique Commercial Registry
Preview the platform with this list at [http://org-id.guide/_preview_branch/MZ-CR](http://org-id.guide/_preview_branch/MZ-CR)  (visiting [http://org-id.guide/list/MZ-CR](http://org-id.guide/list/MZ-CR) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Mozambique Commercial Registry' (MZ-CR)

lists/rs/rs-pib.json
A new list has been proposed with the code RS-PIB
**List title:** Tax identification number register
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/RS-PIB](http://org-id.guide/_preview_branch/RS-PIB)  (visiting [http://org-id.guide/list/RS-PIB](http://org-id.guide/list/RS-PIB) when the preview is active or check the files changed options above.
=> New  registry entry for 'Tax identification number register' (RS-PIB)

lists/my/my-ssm.json
A new list has been proposed with the code MY-SSM
**List title:** Companies Commission of Malaysia
Preview the platform with this list at [http://org-id.guide/_preview_branch/MY-SSM](http://org-id.guide/_preview_branch/MY-SSM)  (visiting [http://org-id.guide/list/MY-SSM](http://org-id.guide/list/MY-SSM) when the preview is active or check the files changed options above.
=> New  registry entry for 'Companies Commission of Malaysia' (MY-SSM)

lists/pt/pt-nippc.json
A new list has been proposed with the code PT-NIPPC
**List title:** Portal of Public Services
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/PT-NIPPC](http://org-id.guide/_preview_branch/PT-NIPPC)  (visiting [http://org-id.guide/list/PT-NIPPC](http://org-id.guide/list/PT-NIPPC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Portal of Public Services' (PT-NIPPC)

lists/kz/kz-bin.json
A new list has been proposed with the code KZ-BIN
**List title:** Business Identification Number (BIN)
Preview the platform with this list at [http://org-id.guide/_preview_branch/KZ-BIN](http://org-id.guide/_preview_branch/KZ-BIN)  (visiting [http://org-id.guide/list/KZ-BIN](http://org-id.guide/list/KZ-BIN) when the preview is active or check the files changed options above.
=> New  registry entry for 'Business Identification Number (BIN)' (KZ-BIN)

lists/md/md-idno.json
A new list has been proposed with the code MD-IDNO
**List title:** Legal entity registration number (IDNO) Moldova
Preview the platform with this list at [http://org-id.guide/_preview_branch/MD-IDNO](http://org-id.guide/_preview_branch/MD-IDNO)  (visiting [http://org-id.guide/list/MD-IDNO](http://org-id.guide/list/MD-IDNO) when the preview is active or check the files changed options above.
=> New  registry entry for 'Legal entity registration number (IDNO) Moldova' (MD-IDNO)

lists/bg/bg-eik.json
A new list has been proposed with the code BG-EIK
**List title:** Commercial Register
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/BG-EIK](http://org-id.guide/_preview_branch/BG-EIK)  (visiting [http://org-id.guide/list/BG-EIK](http://org-id.guide/list/BG-EIK) when the preview is active or check the files changed options above.
=> New  registry entry for 'Commercial Register' (BG-EIK)

lists/hr/hr-oib.json
A new list has been proposed with the code HR-OIB
**List title:** Croatia Court Register
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/HR-OIB](http://org-id.guide/_preview_branch/HR-OIB)  (visiting [http://org-id.guide/list/HR-OIB](http://org-id.guide/list/HR-OIB) when the preview is active or check the files changed options above.
=> New  registry entry for 'Croatia Court Register' (HR-OIB)

lists/hr/hr-mbs.json
A new list has been proposed with the code HR-MBS
**List title:** Croatian Court Business Register
Preview the platform with this list at [http://org-id.guide/_preview_branch/HR-MBS](http://org-id.guide/_preview_branch/HR-MBS)  (visiting [http://org-id.guide/list/HR-MBS](http://org-id.guide/list/HR-MBS) when the preview is active or check the files changed options above.
=> New  registry entry for 'Croatian Court Business Register' (HR-MBS)

lists/hu/hu-afa.json
A new list has been proposed with the code HU-AFA
**List title:** Information and Electronic Company Registration Service
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/HU-AFA](http://org-id.guide/_preview_branch/HU-AFA)  (visiting [http://org-id.guide/list/HU-AFA](http://org-id.guide/list/HU-AFA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Information and Electronic Company Registration Service' (HU-AFA)

lists/kg/kg-inn.json
A new list has been proposed with the code KG-INN
**List title:** Kyrgyz Republic Register of Legal Entities
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-INN](http://org-id.guide/_preview_branch/KG-INN)  (visiting [http://org-id.guide/list/KG-INN](http://org-id.guide/list/KG-INN) when the preview is active or check the files changed options above.
=> New  registry entry for 'Kyrgyz Republic Register of Legal Entities' (KG-INN)

lists/kg/kg-id.json
A new list has been proposed with the code KG-ID
**List title:** Electronic database of legal entities and branches (Krygyzstan)
review (bob)
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-ID](http://org-id.guide/_preview_branch/KG-ID)  (visiting [http://org-id.guide/list/KG-ID](http://org-id.guide/list/KG-ID) when the preview is active or check the files changed options above.
=> New  registry entry for 'Electronic database of legal entities and branches (Krygyzstan)' (KG-ID)

lists/tr/tr-mersis.json
A new list has been proposed with the code TR-MERSIS
**List title:** MERSIS - Central Trade Registry System
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/TR-MERSIS](http://org-id.guide/_preview_branch/TR-MERSIS)  (visiting [http://org-id.guide/list/TR-MERSIS](http://org-id.guide/list/TR-MERSIS) when the preview is active or check the files changed options above.
=> New  registry entry for 'MERSIS - Central Trade Registry System' (TR-MERSIS)

lists/ru/ru-inn.json
A new list has been proposed with the code RU-INN
**List title:** Uniform State Register of Legal Entities of Russian Federation
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/RU-INN](http://org-id.guide/_preview_branch/RU-INN)  (visiting [http://org-id.guide/list/RU-INN](http://org-id.guide/list/RU-INN) when the preview is active or check the files changed options above.
=> New  registry entry for 'Uniform State Register of Legal Entities of Russian Federation' (RU-INN)

lists/ee/ee-kmkr.json
A new list has been proposed with the code EE-KMKR
**List title:** e-Business Register (Estonia)
reviewed estonian business register, added open data links
Preview the platform with this list at [http://org-id.guide/_preview_branch/EE-KMKR](http://org-id.guide/_preview_branch/EE-KMKR)  (visiting [http://org-id.guide/list/EE-KMKR](http://org-id.guide/list/EE-KMKR) when the preview is active or check the files changed options above.
=> New  registry entry for 'e-Business Register (Estonia)' (EE-KMKR)

lists/cz/cz-dic.json
A new list has been proposed with the code CZ-DIC
**List title:** Tax ID (DIČ) Czech Republic
need to review if CZ-ICO covers this
Preview the platform with this list at [http://org-id.guide/_preview_branch/CZ-DIC](http://org-id.guide/_preview_branch/CZ-DIC)  (visiting [http://org-id.guide/list/CZ-DIC](http://org-id.guide/list/CZ-DIC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Tax ID (DIČ) Czech Republic' (CZ-DIC)

lists/il/il-roc.json
A new list has been proposed with the code IL-ROC
**List title:** Registrar of Companies (Israel)
review IL-ROC
Preview the platform with this list at [http://org-id.guide/_preview_branch/IL-ROC](http://org-id.guide/_preview_branch/IL-ROC)  (visiting [http://org-id.guide/list/IL-ROC](http://org-id.guide/list/IL-ROC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Registrar of Companies (Israel)' (IL-ROC)

lists/rs/rs-apr.json
An update to the list with code RS-APR has been proposed
**List title:** Serbian Business Registrations Agency 
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/RS-APR](http://org-id.guide/_preview_branch/RS-APR)  (visiting [http://org-id.guide/list/RS-APR](http://org-id.guide/list/RS-APR) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Serbian Business Registrations Agency ' (RS-APR)

schema/codelist-features.json
=> [#132] Delete duplicated contact address from codelist-feature.json

lists/uz/uz-ktut.json
A new list has been proposed with the code UZ-KTUT
**List title:** United State Register of Corporate Entites
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/UZ-KTUT](http://org-id.guide/_preview_branch/UZ-KTUT)  (visiting [http://org-id.guide/list/UZ-KTUT](http://org-id.guide/list/UZ-KTUT) when the preview is active or check the files changed options above.
=> New  registry entry for 'United State Register of Corporate Entites' (UZ-KTUT)

lists/ae/ae-hfza.json
A new list has been proposed with the code AE-HFZA
**List title:** Hamriyah Free Zone Authority
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-HFZA](http://org-id.guide/_preview_branch/AE-HFZA)  (visiting [http://org-id.guide/list/AE-HFZA](http://org-id.guide/list/AE-HFZA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Hamriyah Free Zone Authority' (AE-HFZA)

lists/ae/ae-saif.json
A new list has been proposed with the code AE-SAIF
**List title:** Sharjah Airport International Free Zone
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-SAIF](http://org-id.guide/_preview_branch/AE-SAIF)  (visiting [http://org-id.guide/list/AE-SAIF](http://org-id.guide/list/AE-SAIF) when the preview is active or check the files changed options above.
=> New  registry entry for 'Sharjah Airport International Free Zone' (AE-SAIF)

lists/ae/ae-uqcci.json
A new list has been proposed with the code AE-UQCCI
**List title:** Umm al-Quwain Chamber of Commerce and Industry
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-UQCCI](http://org-id.guide/_preview_branch/AE-UQCCI)  (visiting [http://org-id.guide/list/AE-UQCCI](http://org-id.guide/list/AE-UQCCI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Umm al-Quwain Chamber of Commerce and Industry' (AE-UQCCI)

lists/ae/ae-adcd.json
A new list has been proposed with the code AE-ADCD
**List title:** Abu Dhabi Commercial Directory
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-ADCD](http://org-id.guide/_preview_branch/AE-ADCD)  (visiting [http://org-id.guide/list/AE-ADCD](http://org-id.guide/list/AE-ADCD) when the preview is active or check the files changed options above.
=> New  registry entry for 'Abu Dhabi Commercial Directory' (AE-ADCD)

lists/ae/ae-afz.json
A new list has been proposed with the code AE-AFZ
**List title:** Ajman Free Zone Authority
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-AFZ](http://org-id.guide/_preview_branch/AE-AFZ)  (visiting [http://org-id.guide/list/AE-AFZ](http://org-id.guide/list/AE-AFZ) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ajman Free Zone Authority' (AE-AFZ)

lists/ae/ae-acci.json
A new list has been proposed with the code AE-ACCI
**List title:** Ajman Chamber of Commerce and Industry
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-ACCI](http://org-id.guide/_preview_branch/AE-ACCI)  (visiting [http://org-id.guide/list/AE-ACCI](http://org-id.guide/list/AE-ACCI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ajman Chamber of Commerce and Industry' (AE-ACCI)

lists/ae/ae-difc.json
A new list has been proposed with the code AE-DIFC
**List title:** Dubai International Financial Centre
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-DIFC](http://org-id.guide/_preview_branch/AE-DIFC)  (visiting [http://org-id.guide/list/AE-DIFC](http://org-id.guide/list/AE-DIFC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Dubai International Financial Centre' (AE-DIFC)

lists/ae/ae-dcci.json
A new list has been proposed with the code AE-DCCI
**List title:** Dubai Chamber of Commerce and Industry 
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-DCCI](http://org-id.guide/_preview_branch/AE-DCCI)  (visiting [http://org-id.guide/list/AE-DCCI](http://org-id.guide/list/AE-DCCI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Dubai Chamber of Commerce and Industry ' (AE-DCCI)

lists/ae/ae-dfsa.json
A new list has been proposed with the code AE-DFSA
**List title:** Dubai Financial Services Authority 
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-DFSA](http://org-id.guide/_preview_branch/AE-DFSA)  (visiting [http://org-id.guide/list/AE-DFSA](http://org-id.guide/list/AE-DFSA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Dubai Financial Services Authority ' (AE-DFSA)

lists/ae/ae-ffz.json
A new list has been proposed with the code AE-FFZ
**List title:** Fujairah Free Zone Company Listing
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-FFZ](http://org-id.guide/_preview_branch/AE-FFZ)  (visiting [http://org-id.guide/list/AE-FFZ](http://org-id.guide/list/AE-FFZ) when the preview is active or check the files changed options above.
=> New  registry entry for 'Fujairah Free Zone Company Listing' (AE-FFZ)

lists/ae/ae-fcci.json
A new list has been proposed with the code AE-FCCI
**List title:** Fujairah Chamber of Commerce and Industry
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-FCCI](http://org-id.guide/_preview_branch/AE-FCCI)  (visiting [http://org-id.guide/list/AE-FCCI](http://org-id.guide/list/AE-FCCI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Fujairah Chamber of Commerce and Industry' (AE-FCCI)

lists/ae/ae-rakia.json
A new list has been proposed with the code AE-RAKIA
**List title:** Ras Al Khaimah Investment Authority
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-RAKIA](http://org-id.guide/_preview_branch/AE-RAKIA)  (visiting [http://org-id.guide/list/AE-RAKIA](http://org-id.guide/list/AE-RAKIA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ras Al Khaimah Investment Authority' (AE-RAKIA)

lists/ae/ae-scci.json
A new list has been proposed with the code AE-SCCI
**List title:** Sharjah Chamber of Commerce and Industry
Reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/AE-SCCI](http://org-id.guide/_preview_branch/AE-SCCI)  (visiting [http://org-id.guide/list/AE-SCCI](http://org-id.guide/list/AE-SCCI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Sharjah Chamber of Commerce and Industry' (AE-SCCI)

lists/jo/jo-ccd.json
=> JO-CCD minor updates [related to #165]

lists/mu/mu-cr.json
#174 
A new list has been proposed with the code MR-CR
**List title:** Companies and Businesses Registration Integrated System, Mauritius
Check the files changed options https://github.com/org-id/register/pull/178/files.
=> New registry entry for 'Companies and Businesses Registration Integrated System, Mauritius' [MU-CR]

lists/es/es-dir3.json
An update to the list with code ES-DIR3 has been proposed
**List title:** Common Directory of Organizational Units and Offices - DIR3
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/ES-DIR3](http://org-id.guide/_preview_branch/ES-DIR3)  (visiting [http://org-id.guide/list/ES-DIR3](http://org-id.guide/list/ES-DIR3) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Common Directory of Organizational Units and Offices - DIR3' (ES-DIR3)

lists/py/py-pgn.json, lists/py/py-ruc.json
Re proposals for addition #180 and #181 
Combing branches into one PR
The PR is subject to review for 7 days after which, if there are no objections, it will be merged.
=> PY-RUC and PY-PGN

lists/tz/tz-brla.json
An update to the list with code TZ-BRLA has been proposed
**List title:** Tanzania Business Registrations and Licensing Agency
update to accessible database
Preview the platform with this list at [http://org-id.guide/_preview_branch/TZ-BRLA](http://org-id.guide/_preview_branch/TZ-BRLA)  (visiting [http://org-id.guide/list/TZ-BRLA](http://org-id.guide/list/TZ-BRLA) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Tanzania Business Registrations and Licensing Agency' (TZ-BRLA)

lists/tz/tz-tra.json
A new list has been proposed with the code TZ-TRA
**List title:** Tanzania Revenue Agency
[#198] - addition of Tanzania Revenue Agency list
Preview the platform with this list at [http://dev.org-id.guide/_preview_branch/TZ-TRA](http://dev.org-id.guide/_preview_branch/TZ-TRA)  (visiting [http://dev.org-id.guide/list/TZ-TRA](http://dev.org-id.guide/list/TZ-TRA) when the preview is active or check the files changed options above.
Unless objections are raised, this update will be **merged after 7 days**.
=> New  registry entry for 'Tanzania Revenue Agency' (TZ-TRA)

lists/gb/gb-pla.json
Link to register was broken, seems to have been moved to main registers site.
=> Update broken link

lists/gh/gh-dsw.json
An update to the list with code GH-DSW has been proposed
**List title:** Department of Social Developments
https://github.com/org-id/register/issues/210
Preview the platform with this list at [http://org-id.guide/_preview_branch/GH-DSW](http://org-id.guide/_preview_branch/GH-DSW)  (visiting [http://org-id.guide/list/GH-DSW](http://org-id.guide/list/GH-DSW) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Department of Social Developments' (GH-DSW)

lists/xi/xi-wikidata.json
From #179 
An update to the list with code XI-WIKIDATA has been proposed
List title: Wikidata
=> Flesh out Wikidata record

lists/bd/bd-nab.json
An update to the list with code BD-NAB has been proposed
**List title:** Bangladesh NGO Affairs Bureau 
Removing redundant URL entry.
Preview the platform with this list at [http://org-id.guide/_preview_branch/BD-NAB](http://org-id.guide/_preview_branch/BD-NAB)  (visiting [http://org-id.guide/list/BD-NAB](http://org-id.guide/list/BD-NAB) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Bangladesh NGO Affairs Bureau ' (BD-NAB)

lists/kr/kr-brn.json
A new list has been proposed with the code KR-BRN
**List title:** National Tax Service Business Registration Number
See https://github.com/org-id/register/issues/208
Preview the platform with this list at [http://org-id.guide/_preview_branch/KR-BRN](http://org-id.guide/_preview_branch/KR-BRN)  (visiting [http://org-id.guide/list/KR-BRN](http://org-id.guide/list/KR-BRN) when the preview is active or check the files changed options above.
=> New  registry entry for 'National Tax Service Business Registration Number' (KR-BRN)

lists/so/so-mpnd.json
A new list has been proposed with the code SO-MPND
**List title:** General Register for Non-Governmental Organizations
Somaliland test
Preview the platform with this list at [http://org-id.guide/_preview_branch/SO-MPND](http://org-id.guide/_preview_branch/SO-MPND)  (visiting [http://org-id.guide/list/SO-MPND](http://org-id.guide/list/SO-MPND) when the preview is active or check the files changed options above.
=> New  registry entry for 'General Register for Non-Governmental Organizations' (SO-MPND)

lists/pk/pk-sec.json
A new list has been proposed with the code PK-SEC
**List title:** Securities and Exchange Commission of Pakistan
Creating new entry for companies in Pakistan
Preview the platform with this list at [http://org-id.guide/_preview_branch/PK-SEC](http://org-id.guide/_preview_branch/PK-SEC)  (visiting [http://org-id.guide/list/PK-SEC](http://org-id.guide/list/PK-SEC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Securities and Exchange Commission of Pakistan' (PK-SEC)

lists/bd/bd-roc.json
A new list has been proposed with the code BD-ROC
**List title:** Bangladesh Office of the Register of Joint Stock Companies and Firms 
Staging request in #240 - closes #240
Preview the platform with this list at [http://org-id.guide/_preview_branch/BD-ROC](http://org-id.guide/_preview_branch/BD-ROC)  (visiting [http://org-id.guide/list/BD-ROC](http://org-id.guide/list/BD-ROC) when the preview is active or check the files changed options above.
=> New  registry entry for 'Bangladesh Office of the Register of Joint Stock Companies and Firms ' (BD-ROC)

lists/ug/ug-ngo.json
A new list has been proposed with the code UG-NGO
**List title:** National Bureau for NGOs (Uganda)
Staging #238 - closes #238
Preview the platform with this list at [http://org-id.guide/_preview_branch/UG-NGO](http://org-id.guide/_preview_branch/UG-NGO)  (visiting [http://org-id.guide/list/UG-NGO](http://org-id.guide/list/UG-NGO) when the preview is active or check the files changed options above.
=> New  registry entry for 'National Bureau for NGOs (Uganda)' (UG-NGO)

lists/il/il-ra.json
A new list has been proposed with the code IL-RA
**List title:** Israel Charity Registry
Adding new entry - addresses #237 - closes #237
Preview the platform with this list at [http://org-id.guide/_preview_branch/IL-RA](http://org-id.guide/_preview_branch/IL-RA)  (visiting [http://org-id.guide/list/IL-RA](http://org-id.guide/list/IL-RA) when the preview is active or check the files changed options above.
=> New  registry entry for 'Israel Charity Registry' (IL-RA)

lists/iq/iq-ngo.json
A new list has been proposed with the code IQ-NGO
**List title:** NGO Directorate (Republic of Iraq)
Preview the platform with this list at [http://org-id.guide/_preview_branch/IQ-NGO](http://org-id.guide/_preview_branch/IQ-NGO)  (visiting [http://org-id.guide/list/IQ-NGO](http://org-id.guide/list/IQ-NGO) when the preview is active or check the files changed options above.
=> New  registry entry for 'NGO Directorate (Republic of Iraq)' (IQ-NGO)

lists/in/in-mca.json
An update to the list with code IN-MCA has been proposed
**List title:** Government of India, Ministry of Corporate Affairs
Updating to include links to search service. 
Preview the platform with this list at [http://org-id.guide/_preview_branch/IN-MCA](http://org-id.guide/_preview_branch/IN-MCA)  (visiting [http://org-id.guide/list/IN-MCA](http://org-id.guide/list/IN-MCA) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Government of India, Ministry of Corporate Affairs' (IN-MCA)

lists/af/af-tin.json
A new list has been proposed with the code AF-TIN
**List title:** Afghanistan Tax Identification Number
addition for #287
Preview the platform with this list at [http://org-id.guide/_preview_branch/AF-TIN](http://org-id.guide/_preview_branch/AF-TIN)  (visiting [http://org-id.guide/list/AF-TIN](http://org-id.guide/list/AF-TIN) when the preview is active or check the files changed options above.
=> New  registry entry for 'Afghanistan Tax Identification Number' (AF-TIN)

lists/ne/ne-dgi.json
A new list has been proposed with the code NE-DGI
**List title:** Tax Directorate
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/NE-DGI](http://org-id.guide/_preview_branch/NE-DGI)  (visiting [http://org-id.guide/list/NE-DGI](http://org-id.guide/list/NE-DGI) when the preview is active or check the files changed options above.
=> New  registry entry for 'Tax Directorate' (NE-DGI)

lists/al/al-qkb.json
A new list has been proposed with the code AL-QKB
**List title:** Albanian National Business Center
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/AL-QKB](http://org-id.guide/_preview_branch/AL-QKB)  (visiting [http://org-id.guide/list/AL-QKB](http://org-id.guide/list/AL-QKB) when the preview is active or check the files changed options above.
=> New  registry entry for 'Albanian National Business Center' (AL-QKB)

lists/es/es-mdj.json
A new list has been proposed with the code ES-MDJ
**List title:** Ministerio de Justicia 
reviewed
Preview the platform with this list at [http://org-id.guide/_preview_branch/ES-MDJ](http://org-id.guide/_preview_branch/ES-MDJ)  (visiting [http://org-id.guide/list/ES-MDJ](http://org-id.guide/list/ES-MDJ) when the preview is active or check the files changed options above.
=> New  registry entry for 'Ministerio de Justicia ' (ES-MDJ)

lists/kg/kg-okpo.json
A new list has been proposed with the code KG-OKPO
**List title:** Electronic database of legal entities and branches (Krygyzstan) OKPO codes
New list for Kyrgyz Republic OKPO codes
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-OKPO](http://org-id.guide/_preview_branch/KG-OKPO)  (visiting [http://org-id.guide/list/KG-OKPO](http://org-id.guide/list/KG-OKPO) when the preview is active or check the files changed options above.
=> New  registry entry for 'Electronic database of legal entities and branches (Krygyzstan) OKPO codes' (KG-OKPO)

lists/kg/kg-tin.json
A new list has been proposed with the code KG-TIN
**List title:** Electronic database of legal entities and branches (Krygyzstan) TIN
Create a new list for Kyrgyz Republic - TIN
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-TIN](http://org-id.guide/_preview_branch/KG-TIN)  (visiting [http://org-id.guide/list/KG-TIN](http://org-id.guide/list/KG-TIN) when the preview is active or check the files changed options above.
=> New  registry entry for 'Electronic database of legal entities and branches (Krygyzstan) TIN' (KG-TIN)

lists/gb/gb-ccscust.json
A new list has been proposed with the code GB-CCSCUST
**List title:** Crown Commercial Services Customers
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-CCSCUST](http://org-id.guide/_preview_branch/GB-CCSCUST)  (visiting [http://org-id.guide/list/GB-CCSCUST](http://org-id.guide/list/GB-CCSCUST) when the preview is active or check the files changed options above.
=> New  registry entry for 'Crown Commercial Services Customers' (GB-CCSCUST)

lists/kg/kg-okpo.json
An update to the list with code KG-OKPO has been proposed
**List title:** Electronic database of legal entities and branches (Krygyzstan) OKPO codes
This edit changes the list of legal structures to encompass a wider range of legal entities that are registered through the Ministry of Justice of the Republic of Kyrgyz.
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-OKPO](http://org-id.guide/_preview_branch/KG-OKPO)  (visiting [http://org-id.guide/list/KG-OKPO](http://org-id.guide/list/KG-OKPO) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Electronic database of legal entities and branches (Krygyzstan) OKPO codes' (KG-OKPO)

lists/kg/kg-tin.json
An update to the list with code KG-TIN has been proposed
**List title:** Electronic database of legal entities and branches (Krygyzstan) TIN
null
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-TIN](http://org-id.guide/_preview_branch/KG-TIN)  (visiting [http://org-id.guide/list/KG-TIN](http://org-id.guide/list/KG-TIN) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Electronic database of legal entities and branches (Krygyzstan) TIN' (KG-TIN)

lists/kg/kg-id.json
An update to the list with code KG-ID has been proposed
**List title:** Electronic database of legal entities and branches (Krygyzstan)
This edit changes the list of legal structures to encompass a wider range of legal entities that are registered through the Ministry of Justice of the Republic of Kyrgyz.
Preview the platform with this list at [http://org-id.guide/_preview_branch/KG-ID](http://org-id.guide/_preview_branch/KG-ID)  (visiting [http://org-id.guide/list/KG-ID](http://org-id.guide/list/KG-ID) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Electronic database of legal entities and branches (Krygyzstan)' (KG-ID)

lists/gh/gh-rgd.json
An update to the list with code GH-RGD has been proposed
**List title:** Registrar General's Department
Updating search instructions
Preview the platform with this list at [http://org-id.guide/_preview_branch/GH-RGD](http://org-id.guide/_preview_branch/GH-RGD)  (visiting [http://org-id.guide/list/GH-RGD](http://org-id.guide/list/GH-RGD) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Registrar General's Department' (GH-RGD)

lists/sl/sl-oarg.json
A new list has been proposed with the code SL-OARG
**List title:** Office of Administrator and Registrar General
Creating a new list for businesses in Sierra Leone
Preview the platform with this list at [http://org-id.guide/_preview_branch/SL-OARG](http://org-id.guide/_preview_branch/SL-OARG)  (visiting [http://org-id.guide/list/SL-OARG](http://org-id.guide/list/SL-OARG) when the preview is active or check the files changed options above.
=> New  registry entry for 'Office of Administrator and Registrar General' (SL-OARG)

lists/gb/gb-mpr.json
An update to the list with code GB-MPR has been proposed
**List title:** Mutuals Public Register
Updated list details following provision of a bulk download.
Preview the platform with this list at [http://org-id.guide/_preview_branch/GB-MPR](http://org-id.guide/_preview_branch/GB-MPR)  (visiting [http://org-id.guide/list/GB-MPR](http://org-id.guide/list/GB-MPR) when the preview is active or check the files changed options above.
=> Updated  registry entry for 'Mutuals Public Register' (GB-MPR)

lists/np/np-ird.json
A new list has been proposed with the code NP-IRD
**List title:** Inland Revenue Department
Preview the platform with this list at [http://org-id.guide/_preview_branch/NP-IRD](http://org-id.guide/_preview_branch/NP-IRD)  (visiting [http://org-id.guide/list/NP-IRD](http://org-id.guide/list/NP-IRD) when the preview is active or check the files changed options above.
=> New  registry entry for 'Inland Revenue Department' (NP-IRD)

lists/id/id-djp.json
A new list has been proposed with the code ID-DJP
**List title:** Director General of Taxes
Preview the platform with this list at [http://org-id.guide/_preview_branch/ID-DJP](http://org-id.guide/_preview_branch/ID-DJP)  (visiting [http://org-id.guide/list/ID-DJP](http://org-id.guide/list/ID-DJP) when the preview is active or check the files changed options above.
=> New  registry entry for 'Director General of Taxes' (ID-DJP)

lists/gb/gb-edu.json
Implements https://github.com/org-id/register/issues/360
=> Correction to GB-EDU

lists/gb/gb-waledu.json
=> New Registry entry for "Register of Schools (Wales) - GB-WALEDU"

lists/gb/gb-scotedu.json
=> New registry entry for "Scottish School Contact Details - GB-SCOTEDU"

lists/am/am-srale.json
Implements https://github.com/org-id/register/issues/386
=> New registry entry for State Register Agency of Legal Entities of Armenia [AM-SRALE]

README.md
This just needs a read-through by someone else before it's merged.
=> Updated readMe to include info about hiatus

issue_template.md
Again - someone else's eyes on this before merge would be good. (Sorry to do these edits as separated PRs, but I decided to use the web UI!)
=> Information about hiatus added to issue template

README.md
Status update mirrors that proposed for the org-id.guide/about page.
=> Updating status message to indicate longer hiatus

issue_template.md
I've added an explicit request in the issue template for a person to mention the data standard that they're working with. I hope that goes some way to helping our workflow while we're in this 'hiatus' period.
@duncandewhurst - asking for your review on the PR to you since you noticed #395 falling between the cracks.
=> Issue template edit - request for open standard info

lists/br/cnpj.json
=> Proposing new list BR-CNPJ

lists/br/br-cnpj.json
Argh. Spotted that the list file wasn't named properly and the example identifiers weren't normalised.
=> Update and rename cnpj.json to br-cnpj.json

lists/cm/cm-niu.json
This is one of Thea's lists, though with a bit more research I uncovered better list info online and have gone for a different list identifier since 'NIU' is the common term for the id.
=> Create cm-niu.json fixes #376

lists/xi/xi-bridge.json
=> Updating record to reflect that the BRIDGE project has closed.

lists/th/th-tin.json
I couldn't find a simple UI for searching for or finding TINs, but there is a SOAP API providing limited validation of TINs.
=> New TH-TIN record fixes #377

lists/fi/fi-vero.json
create register for Finnish VAT number as per proposal https://github.com/org-id/register/issues/508
=> Create fi-vero.json fixes #508

lists/ne/ne-dgi.json
Updated main list url and making list public (as confirmed list)
=> Update ne-dgi.json as a confirmed list

lists/ke/ke-kra.json
Fix #538 - Main list url updated to fix broken link. Other links in the description/text have been checked and still work.
=> Fix #538 - KE-KRA broken link update

lists/in/in-mca.json
Fix #543 - Searchable database link updated and guidance text reviewed
=> Fix #543 - Update IN-MCA

lists/gb/gb-gor.json
Updated to reflect the archiving of the GB-GOR register
=> Update gb-gor.json, fixes #498

lists/ye/ye-cr.json
Adding YE-CR, I've edited the previous stub
=> Update/create ye-cr.json

lists/ph/ph-sec.json
Added search on the SEC website.
=> Update ph-sec.json - implements #562

lists/gb/gb-mpr.json
Fix #493 - Main register url updated and guidance text reviewed.
=> Fix #493 - GB-MPR link update

lists/bd/bd-roc.json
Updated BD-ROC list title to match website and links to the searchable database.
=> Fix #567 - bd-roc.json

lists/id/id-djp.json
Fixes #547 - link to register website has been updated. No searchable online database has been found so guidance text updated accordingly
=> Fix #547 - id-djp.json

lists/na/na-bipa.json
=> Create record for BIPA, na-bipa.json fixes #586

lists/bd/bd-nab.json
Fix #590: 
- register description checked against source page (no changes made)
- link to searchable PDF list of organisations updated to 2024 version
- broken link removed from "Search options"
=> Update bd-nab.json - fix #590

lists/au/au-abn.json, lists/au/au-acnc.json
See #585. This PR contains edits to two lists.
=> Update to Australian lists, fixes #585

lists/xi/xi-ror.json
Fix #600 - main list url and description updated
=> Update XI-ROR (fix #600)
